/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentGrantRequestCreated : Response to an agent's access request: the request it created, plus the URL to hand to the human it acts for. An agent has no browser, so it cannot run the approval itself -- `fulfill_url` is what its owner opens to approve or deny.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentGrantRequestCreated {
    #[serde(rename = "grant_request")]
    pub grant_request: models::GrantRequest,
    #[serde(rename = "fulfill_url")]
    pub fulfill_url: String,
}

impl AgentGrantRequestCreated {
    /// Response to an agent's access request: the request it created, plus the URL to hand to the human it acts for. An agent has no browser, so it cannot run the approval itself -- `fulfill_url` is what its owner opens to approve or deny.
    pub fn new(grant_request: models::GrantRequest, fulfill_url: String) -> AgentGrantRequestCreated {
        AgentGrantRequestCreated {
            grant_request,
            fulfill_url,
        }
    }
}
