/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentCreated : Response returned once when an agent is created, carrying the one-time API token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentCreated {
    #[serde(rename = "agent")]
    pub agent: models::Agent,
    #[serde(rename = "token")]
    pub token: String,
}

impl AgentCreated {
    /// Response returned once when an agent is created, carrying the one-time API token.
    pub fn new(agent: models::Agent, token: String) -> AgentCreated {
        AgentCreated { agent, token }
    }
}
