/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentPssoDeviceState : What authentik currently has stored for this device's Platform SSO registration, so the client can detect drift and repair it
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentPssoDeviceState {
    #[serde(rename = "device_registered")]
    pub device_registered: bool,
    #[serde(rename = "sign_key_id")]
    pub sign_key_id: String,
    #[serde(rename = "enc_key_id")]
    pub enc_key_id: String,
    #[serde(rename = "users")]
    pub users: Vec<models::AgentPssoDeviceStateUser>,
}

impl AgentPssoDeviceState {
    /// What authentik currently has stored for this device's Platform SSO registration, so the client can detect drift and repair it
    pub fn new(
        device_registered: bool,
        sign_key_id: String,
        enc_key_id: String,
        users: Vec<models::AgentPssoDeviceStateUser>,
    ) -> AgentPssoDeviceState {
        AgentPssoDeviceState {
            device_registered,
            sign_key_id,
            enc_key_id,
            users,
        }
    }
}
