/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentCreateRequest : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentCreateRequest {
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<i32>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "expiring", skip_serializing_if = "Option::is_none")]
    pub expiring: Option<bool>,
    #[serde(
        rename = "expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "policy_behavior", skip_serializing_if = "Option::is_none")]
    pub policy_behavior: Option<models::PolicyBehaviorEnum>,
}

impl AgentCreateRequest {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new() -> AgentCreateRequest {
        AgentCreateRequest {
            parent: None,
            label: None,
            expiring: None,
            expires: None,
            policy_behavior: None,
        }
    }
}
