/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentGrantRequestCreateRequest : Body for an agent requesting access for itself. Deliberately narrower than `GrantRequestCreateSerializer`: an agent may not pick its own expiry, which is derived from the granting rules and capped by the agent's own lifetime.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentGrantRequestCreateRequest {
    #[serde(rename = "pbms")]
    pub pbms: Vec<uuid::Uuid>,
}

impl AgentGrantRequestCreateRequest {
    /// Body for an agent requesting access for itself. Deliberately narrower than `GrantRequestCreateSerializer`: an agent may not pick its own expiry, which is derived from the granting rules and capped by the agent's own lifetime.
    pub fn new(pbms: Vec<uuid::Uuid>) -> AgentGrantRequestCreateRequest {
        AgentGrantRequestCreateRequest { pbms }
    }
}
