/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentPssoDeviceStateUser : A user currently registered for Platform SSO on this device
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentPssoDeviceStateUser {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "enclave_key_id")]
    pub enclave_key_id: String,
}

impl AgentPssoDeviceStateUser {
    /// A user currently registered for Platform SSO on this device
    pub fn new(username: String, enclave_key_id: String) -> AgentPssoDeviceStateUser {
        AgentPssoDeviceStateUser {
            username,
            enclave_key_id,
        }
    }
}
