/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Agent : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "username")]
    pub username: String,
    /// User's display name.
    #[serde(rename = "name")]
    pub name: String,
    /// Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(
        rename = "last_login",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_login: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "uid")]
    pub uid: String,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "expiring", skip_serializing_if = "Option::is_none")]
    pub expiring: Option<bool>,
    #[serde(
        rename = "expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "parent")]
    pub parent: models::PartialUser,
    #[serde(rename = "policy_behavior")]
    pub policy_behavior: models::PolicyBehaviorEnum,
    /// Identifier of the agent's API token, so its key can be retrieved/copied later.
    #[serde(rename = "token_identifier", deserialize_with = "Option::deserialize")]
    pub token_identifier: Option<String>,
}

impl Agent {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new(
        pk: i32,
        username: String,
        name: String,
        uid: String,
        uuid: uuid::Uuid,
        parent: models::PartialUser,
        policy_behavior: models::PolicyBehaviorEnum,
        token_identifier: Option<String>,
    ) -> Agent {
        Agent {
            pk,
            username,
            name,
            is_active: None,
            last_login: None,
            email: None,
            attributes: None,
            uid,
            uuid,
            expiring: None,
            expires: None,
            parent,
            policy_behavior,
            token_identifier,
        }
    }
}
