/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectionToken : ConnectionToken Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionToken {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<uuid::Uuid>,
    #[serde(rename = "provider")]
    pub provider: i32,
    #[serde(rename = "provider_obj")]
    pub provider_obj: models::RacProvider,
    #[serde(rename = "device")]
    pub device: uuid::Uuid,
    #[serde(rename = "device_name")]
    pub device_name: String,
    #[serde(rename = "user")]
    pub user: models::PartialUser,
}

impl ConnectionToken {
    /// ConnectionToken Serializer
    pub fn new(
        provider: i32,
        provider_obj: models::RacProvider,
        device: uuid::Uuid,
        device_name: String,
        user: models::PartialUser,
    ) -> ConnectionToken {
        ConnectionToken {
            pk: None,
            provider,
            provider_obj,
            device,
            device_name,
            user,
        }
    }
}
