/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrentBrandFlags {
    /// Upon successful authentication, re-start authentication in other open tabs.
    #[serde(rename = "flows_continuous_login")]
    pub flows_continuous_login: bool,
}

impl CurrentBrandFlags {
    pub fn new(flows_continuous_login: bool) -> CurrentBrandFlags {
        CurrentBrandFlags { flows_continuous_login }
    }
}
