/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrentBrandFlags {
    #[serde(rename = "policies_buffered_access_view")]
    pub policies_buffered_access_view: bool,
    #[serde(rename = "flows_continuous_login")]
    pub flows_continuous_login: bool,
    #[serde(rename = "flows_refresh_others")]
    pub flows_refresh_others: bool,
}

impl CurrentBrandFlags {
    pub fn new(
        policies_buffered_access_view: bool,
        flows_continuous_login: bool,
        flows_refresh_others: bool,
    ) -> CurrentBrandFlags {
        CurrentBrandFlags {
            policies_buffered_access_view,
            flows_continuous_login,
            flows_refresh_others,
        }
    }
}
