/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceAccessGroupRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl DeviceAccessGroupRequest {
    pub fn new(name: String) -> DeviceAccessGroupRequest {
        DeviceAccessGroupRequest { name }
    }
}
