/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceAccessGroup {
    #[serde(rename = "pbm_uuid")]
    pub pbm_uuid: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
}

impl DeviceAccessGroup {
    pub fn new(pbm_uuid: uuid::Uuid, name: String) -> DeviceAccessGroup {
        DeviceAccessGroup { pbm_uuid, name }
    }
}
