/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiagramEdgeTypeEnum {
    #[serde(rename = "proceed")]
    Proceed,
    #[serde(rename = "binding")]
    Binding,
    #[serde(rename = "policy-passed")]
    PolicyPassed,
    #[serde(rename = "policy-denied")]
    PolicyDenied,
    #[serde(rename = "requirement-fulfilled")]
    RequirementFulfilled,
    #[serde(rename = "requirement-unfulfilled")]
    RequirementUnfulfilled,
}

impl std::fmt::Display for DiagramEdgeTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Proceed => write!(f, "proceed"),
            Self::Binding => write!(f, "binding"),
            Self::PolicyPassed => write!(f, "policy-passed"),
            Self::PolicyDenied => write!(f, "policy-denied"),
            Self::RequirementFulfilled => write!(f, "requirement-fulfilled"),
            Self::RequirementUnfulfilled => write!(f, "requirement-unfulfilled"),
        }
    }
}

impl Default for DiagramEdgeTypeEnum {
    fn default() -> DiagramEdgeTypeEnum {
        Self::Proceed
    }
}
