/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiagramNodeTypeEnum {
    #[serde(rename = "flow-start")]
    FlowStart,
    #[serde(rename = "pre-flow-policies")]
    PreFlowPolicies,
    #[serde(rename = "authentication-requirement")]
    AuthenticationRequirement,
    #[serde(rename = "stage")]
    Stage,
    #[serde(rename = "policy")]
    Policy,
    #[serde(rename = "flow-end")]
    FlowEnd,
}

impl std::fmt::Display for DiagramNodeTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FlowStart => write!(f, "flow-start"),
            Self::PreFlowPolicies => write!(f, "pre-flow-policies"),
            Self::AuthenticationRequirement => write!(f, "authentication-requirement"),
            Self::Stage => write!(f, "stage"),
            Self::Policy => write!(f, "policy"),
            Self::FlowEnd => write!(f, "flow-end"),
        }
    }
}

impl Default for DiagramNodeTypeEnum {
    fn default() -> DiagramNodeTypeEnum {
        Self::FlowStart
    }
}
