/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiagramEdge : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagramEdge {
    #[serde(rename = "origin")]
    pub origin: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "type")]
    pub r#type: models::DiagramEdgeTypeEnum,
}

impl DiagramEdge {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new(origin: String, target: String, r#type: models::DiagramEdgeTypeEnum) -> DiagramEdge {
        DiagramEdge { origin, target, r#type }
    }
}
