/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiagramNode : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagramNode {
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "type")]
    pub r#type: models::DiagramNodeTypeEnum,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "verbose_name")]
    pub verbose_name: String,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "pk")]
    pub pk: String,
    #[serde(rename = "component")]
    pub component: String,
    #[serde(rename = "binding_model")]
    pub binding_model: String,
    #[serde(rename = "binding_pk")]
    pub binding_pk: String,
    #[serde(rename = "binding_order", deserialize_with = "Option::deserialize")]
    pub binding_order: Option<i32>,
}

impl DiagramNode {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new(
        identifier: String,
        r#type: models::DiagramNodeTypeEnum,
        name: String,
        verbose_name: String,
        model: String,
        pk: String,
        component: String,
        binding_model: String,
        binding_pk: String,
        binding_order: Option<i32>,
    ) -> DiagramNode {
        DiagramNode {
            identifier,
            r#type,
            name,
            verbose_name,
            model,
            pk,
            component,
            binding_model,
            binding_pk,
            binding_order,
        }
    }
}
