/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlowDiagram : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowDiagram {
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::DiagramNode>,
    #[serde(rename = "edges")]
    pub edges: Vec<models::DiagramEdge>,
}

impl FlowDiagram {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new(nodes: Vec<models::DiagramNode>, edges: Vec<models::DiagramEdge>) -> FlowDiagram {
        FlowDiagram { nodes, edges }
    }
}
