/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GrantRequest : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantRequest {
    #[serde(rename = "created")]
    pub created: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "created_by")]
    pub created_by: models::PartialUser,
    #[serde(rename = "requester_data", skip_serializing_if = "Option::is_none")]
    pub requester_data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "fulfiller_data", skip_serializing_if = "Option::is_none")]
    pub fulfiller_data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "revoked_by", deserialize_with = "Option::deserialize")]
    pub revoked_by: Option<models::PartialUser>,
    #[serde(rename = "agent_owner", deserialize_with = "Option::deserialize")]
    pub agent_owner: Option<models::PartialUser>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(
        rename = "expires",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "status")]
    pub status: models::RequestStatus,
    #[serde(rename = "targets")]
    pub targets: Vec<uuid::Uuid>,
    #[serde(rename = "target_objs")]
    pub target_objs: Vec<models::RequestableTarget>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
}

impl GrantRequest {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new(
        created: chrono::DateTime<chrono::FixedOffset>,
        created_by: models::PartialUser,
        revoked_by: Option<models::PartialUser>,
        agent_owner: Option<models::PartialUser>,
        is_active: bool,
        status: models::RequestStatus,
        targets: Vec<uuid::Uuid>,
        target_objs: Vec<models::RequestableTarget>,
    ) -> GrantRequest {
        GrantRequest {
            created,
            created_by,
            requester_data: None,
            fulfiller_data: None,
            revoked_by,
            agent_owner,
            is_active,
            expires: None,
            status,
            targets,
            target_objs,
            uuid: None,
        }
    }
}
