/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GrantRequestCreateRequest : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantRequestCreateRequest {
    #[serde(rename = "pbms")]
    pub pbms: Vec<uuid::Uuid>,
    /// Optional override for how long the grant should last once approved. Clamped to the granting rule binding(s)' expiry_granted_max.
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
}

impl GrantRequestCreateRequest {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new(pbms: Vec<uuid::Uuid>) -> GrantRequestCreateRequest {
        GrantRequestCreateRequest { pbms, expiry: None }
    }
}
