/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseUserCountRange : Counts of active users added within a date range.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseUserCountRange {
    #[serde(rename = "start")]
    pub start: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "end")]
    pub end: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "interval", deserialize_with = "Option::deserialize")]
    pub interval: Option<String>,
    #[serde(rename = "internal_users_added")]
    pub internal_users_added: i32,
    #[serde(rename = "external_users_added")]
    pub external_users_added: i32,
}

impl LicenseUserCountRange {
    /// Counts of active users added within a date range.
    pub fn new(
        start: chrono::DateTime<chrono::FixedOffset>,
        end: chrono::DateTime<chrono::FixedOffset>,
        interval: Option<String>,
        internal_users_added: i32,
        external_users_added: i32,
    ) -> LicenseUserCountRange {
        LicenseUserCountRange {
            start,
            end,
            interval,
            internal_users_added,
            external_users_added,
        }
    }
}
