/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicenseUserCounts : Current active user totals and counts for requested date ranges.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseUserCounts {
    #[serde(rename = "active_internal_users")]
    pub active_internal_users: i32,
    #[serde(rename = "active_external_users")]
    pub active_external_users: i32,
    #[serde(rename = "ranges")]
    pub ranges: Vec<models::LicenseUserCountRange>,
}

impl LicenseUserCounts {
    /// Current active user totals and counts for requested date ranges.
    pub fn new(
        active_internal_users: i32,
        active_external_users: i32,
        ranges: Vec<models::LicenseUserCountRange>,
    ) -> LicenseUserCounts {
        LicenseUserCounts {
            active_internal_users,
            active_external_users,
            ranges,
        }
    }
}
