/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationModeEnum {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "direct")]
    Direct,
    #[serde(rename = "random_min_reviewers")]
    RandomMinReviewers,
}

impl std::fmt::Display for NotificationModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "all"),
            Self::Direct => write!(f, "direct"),
            Self::RandomMinReviewers => write!(f, "random_min_reviewers"),
        }
    }
}

impl Default for NotificationModeEnum {
    fn default() -> NotificationModeEnum {
        Self::All
    }
}
