/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuth2DynamicClientRegistration : Serializer for OAuth2DynamicClientRegistration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2DynamicClientRegistration {
    #[serde(rename = "pbm_uuid")]
    pub pbm_uuid: uuid::Uuid,
    #[serde(rename = "provider")]
    pub provider: i32,
    /// Group to assign to automatically created applications.
    #[serde(rename = "default_application_group", skip_serializing_if = "Option::is_none")]
    pub default_application_group: Option<String>,
    /// Authorization flow applied to dynamically registered clients.
    #[serde(
        rename = "override_authorization_flow",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub override_authorization_flow: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "override_invalidation_flow",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub override_invalidation_flow: Option<Option<uuid::Uuid>>,
    /// Scope mappings applied to dynamically registered clients.
    #[serde(rename = "override_property_mappings", skip_serializing_if = "Option::is_none")]
    pub override_property_mappings: Option<Vec<uuid::Uuid>>,
    /// Maximum access token validity for registered clients (Format: hours=1;minutes=2;seconds=3).
    #[serde(rename = "access_token_validity", skip_serializing_if = "Option::is_none")]
    pub access_token_validity: Option<String>,
    /// Maximum refresh token validity for registered clients (Format: hours=1;minutes=2;seconds=3).
    #[serde(rename = "refresh_token_validity", skip_serializing_if = "Option::is_none")]
    pub refresh_token_validity: Option<String>,
    /// If empty, all grant types are allowed.
    #[serde(rename = "allowed_grant_types", skip_serializing_if = "Option::is_none")]
    pub allowed_grant_types: Option<Vec<models::GrantTypeEnum>>,
    #[serde(rename = "policy_engine_mode", skip_serializing_if = "Option::is_none")]
    pub policy_engine_mode: Option<models::PolicyEngineMode>,
}

impl OAuth2DynamicClientRegistration {
    /// Serializer for OAuth2DynamicClientRegistration
    pub fn new(pbm_uuid: uuid::Uuid, provider: i32) -> OAuth2DynamicClientRegistration {
        OAuth2DynamicClientRegistration {
            pbm_uuid,
            provider,
            default_application_group: None,
            override_authorization_flow: None,
            override_invalidation_flow: None,
            override_property_mappings: None,
            access_token_validity: None,
            refresh_token_validity: None,
            allowed_grant_types: None,
            policy_engine_mode: None,
        }
    }
}
