/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OffboardingActionEnum {
    #[serde(rename = "deactivate")]
    Deactivate,
    #[serde(rename = "delete")]
    Delete,
}

impl std::fmt::Display for OffboardingActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Deactivate => write!(f, "deactivate"),
            Self::Delete => write!(f, "delete"),
        }
    }
}

impl Default for OffboardingActionEnum {
    fn default() -> OffboardingActionEnum {
        Self::Deactivate
    }
}
