/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2025.12.5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperatingSystemRequest {
    #[serde(rename = "family")]
    pub family: models::DeviceFactsOsFamily,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "arch")]
    pub arch: String,
}

impl OperatingSystemRequest {
    pub fn new(family: models::DeviceFactsOsFamily, arch: String) -> OperatingSystemRequest {
        OperatingSystemRequest {
            family,
            name: None,
            version: None,
            arch,
        }
    }
}
