/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedRequestRuleChildBindingList {
    #[serde(rename = "pagination")]
    pub pagination: models::Pagination,
    #[serde(rename = "results")]
    pub results: Vec<models::RequestRuleChildBinding>,
    #[serde(rename = "autocomplete")]
    pub autocomplete: std::collections::HashMap<String, serde_json::Value>,
}

impl PaginatedRequestRuleChildBindingList {
    pub fn new(
        pagination: models::Pagination,
        results: Vec<models::RequestRuleChildBinding>,
        autocomplete: std::collections::HashMap<String, serde_json::Value>,
    ) -> PaginatedRequestRuleChildBindingList {
        PaginatedRequestRuleChildBindingList {
            pagination,
            results,
            autocomplete,
        }
    }
}
