/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedRequestRuleChildBindingRequest {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "binding", skip_serializing_if = "Option::is_none")]
    pub binding: Option<uuid::Uuid>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<uuid::Uuid>,
}

impl PatchedRequestRuleChildBindingRequest {
    pub fn new() -> PatchedRequestRuleChildBindingRequest {
        PatchedRequestRuleChildBindingRequest {
            uuid: None,
            binding: None,
            target: None,
        }
    }
}
