/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc7
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedGrantRequestFulfillRequest : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedGrantRequestFulfillRequest {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::RequestStatus>,
}

impl PatchedGrantRequestFulfillRequest {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new() -> PatchedGrantRequestFulfillRequest {
        PatchedGrantRequestFulfillRequest {
            data: None,
            status: None,
        }
    }
}
