/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc6
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedRequestRuleBindingRequest : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedRequestRuleBindingRequest {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "policy_engine_mode", skip_serializing_if = "Option::is_none")]
    pub policy_engine_mode: Option<models::PolicyEngineMode>,
    #[serde(rename = "rule", skip_serializing_if = "Option::is_none")]
    pub rule: Option<uuid::Uuid>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<uuid::Uuid>,
    /// How long a request against this binding stays pending before it automatically lapses if not approved or denied.
    #[serde(rename = "expiry_pending", skip_serializing_if = "Option::is_none")]
    pub expiry_pending: Option<String>,
    /// The maximum duration a grant approved against this binding can last.
    #[serde(rename = "expiry_granted_max", skip_serializing_if = "Option::is_none")]
    pub expiry_granted_max: Option<String>,
}

impl PatchedRequestRuleBindingRequest {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new() -> PatchedRequestRuleBindingRequest {
        PatchedRequestRuleBindingRequest {
            uuid: None,
            policy_engine_mode: None,
            rule: None,
            target: None,
            expiry_pending: None,
            expiry_granted_max: None,
        }
    }
}
