/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedRequestRuleRequest : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedRequestRuleRequest {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "policy_engine_mode", skip_serializing_if = "Option::is_none")]
    pub policy_engine_mode: Option<models::PolicyEngineMode>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "notification_transports", skip_serializing_if = "Option::is_none")]
    pub notification_transports: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "notification_mode", skip_serializing_if = "Option::is_none")]
    pub notification_mode: Option<models::NotificationModeEnum>,
    #[serde(rename = "min_reviewers", skip_serializing_if = "Option::is_none")]
    pub min_reviewers: Option<u16>,
    #[serde(rename = "min_reviewers_is_per_group", skip_serializing_if = "Option::is_none")]
    pub min_reviewers_is_per_group: Option<bool>,
    #[serde(
        rename = "request_flow",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub request_flow: Option<Option<uuid::Uuid>>,
}

impl PatchedRequestRuleRequest {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new() -> PatchedRequestRuleRequest {
        PatchedRequestRuleRequest {
            uuid: None,
            policy_engine_mode: None,
            name: None,
            notification_transports: None,
            notification_mode: None,
            min_reviewers: None,
            min_reviewers_is_per_group: None,
            request_flow: None,
        }
    }
}
