/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PolicyBehaviorEnum {
    #[serde(rename = "mirror")]
    Mirror,
    #[serde(rename = "copy")]
    Copy,
    #[serde(rename = "none")]
    None,
}

impl std::fmt::Display for PolicyBehaviorEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Mirror => write!(f, "mirror"),
            Self::Copy => write!(f, "copy"),
            Self::None => write!(f, "none"),
        }
    }
}

impl Default for PolicyBehaviorEnum {
    fn default() -> PolicyBehaviorEnum {
        Self::Mirror
    }
}
