/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RacConnectionOverride : RACConnectionOverride Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RacConnectionOverride {
    /// Hostname/IP to connect to. Optionally specify the port.
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "protocol")]
    pub protocol: models::ProtocolEnum,
}

impl RacConnectionOverride {
    /// RACConnectionOverride Serializer
    pub fn new(host: String, protocol: models::ProtocolEnum) -> RacConnectionOverride {
        RacConnectionOverride { host, protocol }
    }
}
