/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RacDeviceProtocol : A protocol a device can be connected to with
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RacDeviceProtocol {
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "launch_url", deserialize_with = "Option::deserialize")]
    pub launch_url: Option<String>,
}

impl RacDeviceProtocol {
    /// A protocol a device can be connected to with
    pub fn new(protocol: String, launch_url: Option<String>) -> RacDeviceProtocol {
        RacDeviceProtocol { protocol, launch_url }
    }
}
