/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RacDevice : Device as it can be launched through a RAC provider. Deliberately does not include any connection settings, as this is also used by end-users launching a connection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RacDevice {
    #[serde(rename = "device_uuid", skip_serializing_if = "Option::is_none")]
    pub device_uuid: Option<uuid::Uuid>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "protocols")]
    pub protocols: Vec<models::RacDeviceProtocol>,
    /// Primary key of this device's connection override, if it has one
    #[serde(rename = "override_pk", deserialize_with = "Option::deserialize")]
    pub override_pk: Option<i32>,
}

impl RacDevice {
    /// Device as it can be launched through a RAC provider. Deliberately does not include any connection settings, as this is also used by end-users launching a connection.
    pub fn new(name: String, protocols: Vec<models::RacDeviceProtocol>, override_pk: Option<i32>) -> RacDevice {
        RacDevice {
            device_uuid: None,
            name,
            protocols,
            override_pk,
        }
    }
}
