/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RacConnectionOverrideRequest : RACConnectionOverride Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RacConnectionOverrideRequest {
    /// Hostname/IP to connect to. Optionally specify the port.
    #[serde(rename = "host")]
    pub host: String,
    #[serde(rename = "protocol")]
    pub protocol: models::ProtocolEnum,
}

impl RacConnectionOverrideRequest {
    /// RACConnectionOverride Serializer
    pub fn new(host: String, protocol: models::ProtocolEnum) -> RacConnectionOverrideRequest {
        RacConnectionOverrideRequest { host, protocol }
    }
}
