/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.5.0-rc2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RedirectUriTypeEnum {
    #[serde(rename = "authorization")]
    Authorization,
    #[serde(rename = "logout")]
    Logout,
}

impl std::fmt::Display for RedirectUriTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Authorization => write!(f, "authorization"),
            Self::Logout => write!(f, "logout"),
        }
    }
}

impl Default for RedirectUriTypeEnum {
    fn default() -> RedirectUriTypeEnum {
        Self::Authorization
    }
}
