/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RelatedTarget : Simplified related target object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedTarget {
    /// Return object's verbose_name
    #[serde(rename = "verbose_name")]
    pub verbose_name: String,
    /// Return object's plural verbose_name
    #[serde(rename = "verbose_name_plural")]
    pub verbose_name_plural: String,
    /// Return internal model name
    #[serde(rename = "meta_model_name")]
    pub meta_model_name: String,
    #[serde(rename = "pbm_uuid")]
    pub pbm_uuid: String,
    #[serde(rename = "label")]
    pub label: String,
}

impl RelatedTarget {
    /// Simplified related target object
    pub fn new(
        verbose_name: String,
        verbose_name_plural: String,
        meta_model_name: String,
        pbm_uuid: String,
        label: String,
    ) -> RelatedTarget {
        RelatedTarget {
            verbose_name,
            verbose_name_plural,
            meta_model_name,
            pbm_uuid,
            label,
        }
    }
}
