/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestRuleBindingRequest : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestRuleBindingRequest {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "policy_engine_mode", skip_serializing_if = "Option::is_none")]
    pub policy_engine_mode: Option<models::PolicyEngineMode>,
    #[serde(rename = "rule")]
    pub rule: uuid::Uuid,
    #[serde(rename = "target")]
    pub target: uuid::Uuid,
    /// How long a request against this binding stays pending before it automatically lapses if not approved or denied.
    #[serde(rename = "expiry_pending", skip_serializing_if = "Option::is_none")]
    pub expiry_pending: Option<String>,
    /// The maximum duration a grant approved against this binding can last.
    #[serde(rename = "expiry_granted_max", skip_serializing_if = "Option::is_none")]
    pub expiry_granted_max: Option<String>,
}

impl RequestRuleBindingRequest {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new(rule: uuid::Uuid, target: uuid::Uuid) -> RequestRuleBindingRequest {
        RequestRuleBindingRequest {
            uuid: None,
            policy_engine_mode: None,
            rule,
            target,
            expiry_pending: None,
            expiry_granted_max: None,
        }
    }
}
