/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc4
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestRuleBinding : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestRuleBinding {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "pbm_uuid")]
    pub pbm_uuid: uuid::Uuid,
    #[serde(rename = "policy_engine_mode", skip_serializing_if = "Option::is_none")]
    pub policy_engine_mode: Option<models::PolicyEngineMode>,
    #[serde(rename = "rule")]
    pub rule: uuid::Uuid,
    #[serde(rename = "rule_obj")]
    pub rule_obj: models::RequestRule,
    #[serde(rename = "target")]
    pub target: uuid::Uuid,
    #[serde(rename = "related")]
    pub related: Vec<uuid::Uuid>,
    #[serde(rename = "related_obj")]
    pub related_obj: Vec<models::RelatedTarget>,
    /// How long a request against this binding stays pending before it automatically lapses if not approved or denied.
    #[serde(rename = "expiry_pending", skip_serializing_if = "Option::is_none")]
    pub expiry_pending: Option<String>,
    /// The maximum duration a grant approved against this binding can last.
    #[serde(rename = "expiry_granted_max", skip_serializing_if = "Option::is_none")]
    pub expiry_granted_max: Option<String>,
}

impl RequestRuleBinding {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new(
        pbm_uuid: uuid::Uuid,
        rule: uuid::Uuid,
        rule_obj: models::RequestRule,
        target: uuid::Uuid,
        related: Vec<uuid::Uuid>,
        related_obj: Vec<models::RelatedTarget>,
    ) -> RequestRuleBinding {
        RequestRuleBinding {
            uuid: None,
            pbm_uuid,
            policy_engine_mode: None,
            rule,
            rule_obj,
            target,
            related,
            related_obj,
            expiry_pending: None,
            expiry_granted_max: None,
        }
    }
}
