/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestableTarget : Generic representation of a single request target: whatever was actually requested (an Application, an Application Entitlement, ...), always paired with the parent it belongs to, so the UI/audit trail has that context even when the request itself was scoped narrower than the whole app.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestableTarget {
    /// Return object's verbose_name
    #[serde(rename = "verbose_name")]
    pub verbose_name: String,
    /// Return object's plural verbose_name
    #[serde(rename = "verbose_name_plural")]
    pub verbose_name_plural: String,
    /// Return internal model name
    #[serde(rename = "meta_model_name")]
    pub meta_model_name: String,
    #[serde(rename = "pbm_uuid")]
    pub pbm_uuid: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "parent", deserialize_with = "Option::deserialize")]
    pub parent: Option<models::Application>,
}

impl RequestableTarget {
    /// Generic representation of a single request target: whatever was actually requested (an Application, an Application Entitlement, ...), always paired with the parent it belongs to, so the UI/audit trail has that context even when the request itself was scoped narrower than the whole app.
    pub fn new(
        verbose_name: String,
        verbose_name_plural: String,
        meta_model_name: String,
        pbm_uuid: String,
        label: String,
        parent: Option<models::Application>,
    ) -> RequestableTarget {
        RequestableTarget {
            verbose_name,
            verbose_name_plural,
            meta_model_name,
            pbm_uuid,
            label,
            parent,
        }
    }
}
