/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestRuleChildBindingRequest {
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<uuid::Uuid>,
    #[serde(rename = "binding")]
    pub binding: uuid::Uuid,
    #[serde(rename = "target")]
    pub target: uuid::Uuid,
}

impl RequestRuleChildBindingRequest {
    pub fn new(binding: uuid::Uuid, target: uuid::Uuid) -> RequestRuleChildBindingRequest {
        RequestRuleChildBindingRequest {
            uuid: None,
            binding,
            target,
        }
    }
}
