/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestContentTypeEnum {
    #[serde(rename = "application/x-www-form-urlencoded")]
    ApplicationSlashXWwwFormUrlencoded,
    #[serde(rename = "application/json")]
    ApplicationSlashJson,
}

impl std::fmt::Display for RequestContentTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ApplicationSlashXWwwFormUrlencoded => write!(f, "application/x-www-form-urlencoded"),
            Self::ApplicationSlashJson => write!(f, "application/json"),
        }
    }
}

impl Default for RequestContentTypeEnum {
    fn default() -> RequestContentTypeEnum {
        Self::ApplicationSlashXWwwFormUrlencoded
    }
}
