/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResumeOnMatchFailuresEnum {
    #[serde(rename = "missing_property")]
    MissingProperty,
}

impl std::fmt::Display for ResumeOnMatchFailuresEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MissingProperty => write!(f, "missing_property"),
        }
    }
}

impl Default for ResumeOnMatchFailuresEnum {
    fn default() -> ResumeOnMatchFailuresEnum {
        Self::MissingProperty
    }
}
