/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServiceBindMethodEnum {
    #[serde(rename = "simple")]
    Simple,
    #[serde(rename = "sasl_external")]
    SaslExternal,
}

impl std::fmt::Display for ServiceBindMethodEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Simple => write!(f, "simple"),
            Self::SaslExternal => write!(f, "sasl_external"),
        }
    }
}

impl Default for ServiceBindMethodEnum {
    fn default() -> ServiceBindMethodEnum {
        Self::Simple
    }
}
