/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerLogRequest : Base serializer class which doesn't implement create/update methods
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerLogRequest {
    #[serde(rename = "message")]
    pub message: String,
}

impl ServerLogRequest {
    /// Base serializer class which doesn't implement create/update methods
    pub fn new(message: String) -> ServerLogRequest {
        ServerLogRequest { message }
    }
}
