/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc7
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserOffboarding : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserOffboarding {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "user")]
    pub user: i32,
    #[serde(rename = "user_obj")]
    pub user_obj: models::PartialUser,
    /// Absolute time at which the offboarding action is executed.
    #[serde(rename = "scheduled_at")]
    pub scheduled_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::OffboardingActionEnum>,
    /// Revoke all of the user's sessions when offboarding.
    #[serde(rename = "revoke_sessions", skip_serializing_if = "Option::is_none")]
    pub revoke_sessions: Option<bool>,
    /// Revoke all of the user's tokens when offboarding.
    #[serde(rename = "revoke_tokens", skip_serializing_if = "Option::is_none")]
    pub revoke_tokens: Option<bool>,
    #[serde(rename = "status")]
    pub status: models::OffboardingStatusEnum,
    #[serde(rename = "created_by_obj")]
    pub created_by_obj: models::PartialUser,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "executed_at", deserialize_with = "Option::deserialize")]
    pub executed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl UserOffboarding {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new(
        id: uuid::Uuid,
        user: i32,
        user_obj: models::PartialUser,
        scheduled_at: chrono::DateTime<chrono::FixedOffset>,
        status: models::OffboardingStatusEnum,
        created_by_obj: models::PartialUser,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        executed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    ) -> UserOffboarding {
        UserOffboarding {
            id,
            user,
            user_obj,
            scheduled_at,
            action: None,
            revoke_sessions: None,
            revoke_tokens: None,
            status,
            created_by_obj,
            created_at,
            executed_at,
        }
    }
}
