/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc2
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserOffboardingRequest : Mixin to validate that a valid enterprise license exists before allowing to save the object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserOffboardingRequest {
    #[serde(rename = "user")]
    pub user: i32,
    /// Absolute time at which the offboarding action is executed.
    #[serde(rename = "scheduled_at")]
    pub scheduled_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::OffboardingActionEnum>,
    /// Revoke all of the user's sessions when offboarding.
    #[serde(rename = "revoke_sessions", skip_serializing_if = "Option::is_none")]
    pub revoke_sessions: Option<bool>,
    /// Revoke all of the user's tokens when offboarding.
    #[serde(rename = "revoke_tokens", skip_serializing_if = "Option::is_none")]
    pub revoke_tokens: Option<bool>,
}

impl UserOffboardingRequest {
    /// Mixin to validate that a valid enterprise license exists before allowing to save the object
    pub fn new(user: i32, scheduled_at: chrono::DateTime<chrono::FixedOffset>) -> UserOffboardingRequest {
        UserOffboardingRequest {
            user,
            scheduled_at,
            action: None,
            revoke_sessions: None,
            revoke_tokens: None,
        }
    }
}
