/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc3
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSwitchRequest : Request to add or switch users in the current browser.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSwitchRequest {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::UserSwitchActionEnum>,
    #[serde(rename = "user_pk", skip_serializing_if = "Option::is_none")]
    pub user_pk: Option<i32>,
}

impl UserSwitchRequest {
    /// Request to add or switch users in the current browser.
    pub fn new() -> UserSwitchRequest {
        UserSwitchRequest {
            action: None,
            user_pk: None,
        }
    }
}
