/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.8.0-rc5
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSwitchResponse : Redirect returned after planning a user switch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSwitchResponse {
    #[serde(rename = "redirect")]
    pub redirect: String,
}

impl UserSwitchResponse {
    /// Redirect returned after planning a user switch.
    pub fn new(redirect: String) -> UserSwitchResponse {
        UserSwitchResponse { redirect }
    }
}
