/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserSwitchActionEnum {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "switch")]
    Switch,
}

impl std::fmt::Display for UserSwitchActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Add => write!(f, "add"),
            Self::Switch => write!(f, "switch"),
        }
    }
}

impl Default for UserSwitchActionEnum {
    fn default() -> UserSwitchActionEnum {
        Self::Add
    }
}
