/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WsFedSamlVersionEnum {
    #[serde(rename = "1.1")]
    Variant11,
    #[serde(rename = "2.0")]
    Variant20,
}

impl std::fmt::Display for WsFedSamlVersionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant11 => write!(f, "1.1"),
            Self::Variant20 => write!(f, "2.0"),
        }
    }
}

impl Default for WsFedSamlVersionEnum {
    fn default() -> WsFedSamlVersionEnum {
        Self::Variant11
    }
}
